### ISSUE TITLE
Export to PDF gives Class "Barryvdh\Snappy\Facades\SnappyPdf" not found

### ISSUE THREAD

**Issue by invaders-xx** [alperenersoy/filament-export#7]
Your package has also  barryvdh/laravel-snappy dependency

**Comment by alperenersoy** [comment]
Are you using with default settings or with ->snappy() or use_snappy=true in the config file? Can you share a screenshot of the error?

**Comment by invaders-xx** [comment]
there is no use_snappy=true in the config file I published

**Comment by invaders-xx** [comment]
I have installed the package manually and when I export to PDF, no error but nothing happens : no pdf generated

**Comment by alperenersoy** [comment]
Snappy needs to be configured to work. But you don't want to use it right? If you don't could you please share the error before by removing the snappy package from composer.json? If you want to use see [barryvdh/laravel-snappy](https://github.com/barryvdh/laravel-snappy). Because you need to install wkhtmltopdf and provide the binary path in config file of laravel-snappy by publishing it.

> I have installed the package manually and when I export to PDF, no error but nothing happens : no pdf generated

**Comment by alperenersoy** [comment]
> there is no use_snappy=true in the config file I published

Can you republish it or add yourself? It should be there.

**Comment by alperenersoy** [comment]
Also check https://github.com/alperenersoy/filament-export/pull/8.

**Comment by invaders-xx** [comment]
> Snappy needs to be configured to work. But you don't want to use it right? If you don't could you please share the error before by removing the snappy package from composer.json? If you want to use see [barryvdh/laravel-snappy](https://github.com/barryvdh/laravel-snappy). Because you need to install wkhtmltopdf and provide the binary path in config file of laravel-snappy by publishing it.
> 
> > I have installed the package manually and when I export to PDF, no error but nothing happens : no pdf generated

I did install wkhtmltopdf and provide the binary path in config file

**Comment by invaders-xx** [comment]
> > there is no use_snappy=true in the config file I published
> 
> Can you republish it or add yourself? It should be there.

I republish and works fine now with use_snappy=false

When use_snappy=true I got:
Uncaught (in promise) SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at index.js:69:58

[barryvdh/laravel-snappy](https://github.com/barryvdh/laravel-snappy) and wkhtmltopdf  are installed

**Comment by alperenersoy** [comment]
which `index.js` is this? can it be related to something else? because we shouldn't have any index.js or js dependency related to this package. If you think it's not could you please provide detailed error info to debug or repo to reproduce?

and if you are on windows please try these steps:

1. install [wkhtmltopdf-windows](https://github.com/wemersonjanuario/wkhtmltopdf-windows) instead the original one
2. be sure about any directory in the binary file path doesn't have space in its folder name. (maybe move the binary to sth like C:/snappy)

thanks.

**Comment by invaders-xx** [comment]
Hi, I am on OSX using valet

**Comment by alperenersoy** [comment]
have you tried the same configuration with fresh filament installation? I think it's related to something else.
